server:
  port: 8080

affordmed:
  logging:
    baseUrl: "http://4.224.186.213/evaluation-service"
    logEndpoint: "/log"
    token: "default-log-token"
  api:
    baseUrl: "http://4.224.186.213/evaluation-service"
    authEndpoint: "/auth"
    depotsEndpoint: "/depots"
    vehiclesEndpoint: "/vehicles/tasks"
    clientID: "82e3b65a-3082-4d8b-9263-431e82d602f3"
    clientSecret: "xYmJsgZNCesNRhQF"

spring:
  application:
    name: vehicle-maintenance-scheduler
